# Société 

In [2]:
import matplotlib.pyplot as plt
import numpy as np
import random



Le premier paramètre que nous allons étudier est le le facteur socio-economique. Alors nous allons nous basé en premier lieu sur un système catégorisé : les riches et les pauvres. 
La classe moyenne a riche sera modélisée par des 1 et la classe pauvre par des 0.



In [34]:
def tableauBase(P):
    """les 0 sont les pauvres et 1 les riches."""
    tableau_de_zero_un = np.zeros((20,20), dtype='i') #np.zeros : renvoie un tableau 1D de 20 zero (lignes) et 20 zero (colonnes)
    for i in range(len(tableau_de_zero_un)): 
        for j in range(len(tableau_de_zero_un)):
            if random.random() < P :
                tableau_de_zero_un[i,j] = 1

    print(tableau_de_zero_un)
    
    return tableau_de_zero_un
    
tab_base = tableauBase(0.6)



[[0 1 0 1 1 1 1 1 0 1 1 1 1 0 0 0 1 1 1 0]
 [0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 1 1 0 0 0]
 [0 1 0 1 1 1 1 1 1 0 0 0 0 0 0 1 0 1 0 0]
 [1 0 1 0 0 1 1 1 0 1 1 0 0 0 1 1 1 0 0 1]
 [0 1 1 1 0 1 1 0 1 1 1 0 0 1 1 1 0 1 1 1]
 [0 0 1 1 1 1 0 1 1 0 1 0 1 1 1 1 1 0 0 0]
 [0 0 1 1 1 1 1 0 0 0 1 1 0 1 1 0 1 0 0 0]
 [1 1 0 1 1 1 0 1 1 0 0 0 1 1 1 1 1 0 1 0]
 [1 1 0 1 1 0 1 0 1 1 0 1 0 1 0 1 1 1 0 0]
 [0 1 1 1 0 0 1 1 0 0 0 0 0 0 1 1 1 0 1 1]
 [0 0 1 1 1 1 0 0 1 1 1 1 0 1 0 1 0 1 0 0]
 [1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 0 1 0 1 1]
 [1 0 1 1 0 0 1 1 0 0 0 0 1 1 0 0 0 0 1 1]
 [0 1 0 1 1 1 0 0 0 0 1 1 1 0 1 0 0 1 0 1]
 [0 1 1 0 0 1 1 1 0 1 1 1 0 1 1 1 0 1 0 0]
 [0 1 0 1 0 0 0 1 1 1 0 1 0 1 0 1 1 0 1 1]
 [0 1 0 1 0 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1]
 [1 0 0 1 0 1 0 1 1 1 0 0 1 0 1 1 1 1 0 0]
 [1 0 1 1 1 1 1 1 1 0 1 0 0 1 1 1 0 1 1 1]
 [1 1 0 1 0 1 1 0 1 1 1 1 1 1 0 0 0 1 0 0]]


In [71]:
def verifpop(tabF):
    tab = tabF
    comptC = 0 #compteur consommateurs 
    comptNC = 0 #compteur non-consommateurs 
    for i in range(len(tab)) : #parcours de la matrice 
        for j in range(len(tab)) :#parcours de la matrice 
            if  i+1 <= len(tab) and i-1 >= 0 and  j+1 <= len(tab) and j-1 >= 0:
                if tab[i,j] == 1:
                    comptC = comptC +1
                if tab[i,j] == 0:
                    comptNC = comptNC +1
    return comptC + comptNC


print("Population  :",verifpop(tab_base))

Population  : 361


Ensuite, une nouvelle matrice pour modéliser les consommateurs. La présence 4 '0' créé des consommateurs (-1).

In [28]:
def influence_se(tab):  
    """un carré de 0 crée un groupe de consommateurs (nommé -1)"""
    tableau = tab.copy()
    for i in range(len(tableau)) :
        for j in range(len(tableau)) :
            if  i+1 < len(tableau) and i-1 >= 0 and  j+1 < len(tableau) and j-1 >= 0:
                 if tableau[i,j] == 0 and tableau[i+1,j]==0  and tableau[i,j+1]==0 and tableau[i+1,j+1]==0 :
                    tableau[i,j] = -1
                    tableau[i+1,j]=-1 
                    tableau[i,j+1]=-1
                    tableau[i+1,j+1]=-1           
   
    return tableau

print(influence_se(tab_base))

[[ 0  0  0 ...  1  0  1]
 [ 0  0  0 ...  1  1  1]
 [ 0  1  1 ...  1  1  1]
 ...
 [ 0  1 -1 ... -1  0  1]
 [ 1  1 -1 ... -1  0  1]
 [ 0  1  1 ...  1  0  1]]


Le voisinnage : Lorsque un individu est entouré de -1, il voudra déménager. 

In [46]:
def voisins(tab, rowNumber, columnNumber):
    '''
    fonction pour récupérer les voisins
    '''
    N = []
    for i in range(rowNumber-1, rowNumber+2):
        for j in range(columnNumber-1, columnNumber+2):
            if  (i >= 0 and i < tab.shape[0]) and (j >= 0 and j < tab.shape[1]) and ((i,j)!=(rowNumber,columnNumber)):
                N.append(tab[i,j])
    return N


In [49]:
def moyenne_voisins(tab,i,j):
    '''
    Calcul de la moyenne des valeurs voisinnes
    '''
    N = voisins(tab,i,j)
    return sum(N)/len(N)
    
moyenne_voisins(tab_base,2,3)


0.375

In [61]:
def demenagement(tableau):
    """demande de demenagement apres parcours de la matrice"""
    #demande : list[int]
    demande = []
    for i in range(len(tableau)) :
        for j in range(len(tableau)) :
                if (tableau[i,j] == 1 and  moyenne_voisins(tableau,i,j) < 0.5) or (tableau[i,j] == 0 and  moyenne_voisins(tableau,i,j) > 0.5) :
                    demande.append(tableau[i,j])
                                            
    return demande


In [73]:
def nvpop()#creation de la nouvelle population 

In [77]:
def n_generations(tab_base,n):
    """ transformation de la ville """
    
    ancienneV = tab_base
    nouvelleV = nvpop()
    plt.matshow(ancienneV)
    
    for nb in range(0,n-1):
        
        Ldemenag = demenagement(ancienneV)
        
        print("nombre de demenagement :",len(Ldemenag))
        
        
    print("rajout de la creation des consommateurs")
    plt.matshow(influence_se(nouvelleV))#de la nouvelle population
    plt.show()
    
    print("nb pers :",verifpop(nouvelleV))#vérification de la nouvelle population cad ancienneVille - nouvelleVille
    return 0 

tabF=n_generations(tab_base,10)


SyntaxError: invalid syntax (<ipython-input-77-997a614d1436>, line 19)