# Société 

In [3]:
import matplotlib.pyplot as plt
import numpy as np
import random



Le premier paramètre que nous allons étudier est le le facteur socio-economique. Alors nous allons nous basé en premier lieu sur un système catégorisé : les riches et les pauvres. 
La classe moyenne a riche sera modélisée par des 1 et la classe pauvre par des 0.



In [4]:
def tableauBase(P):
    """les 0 sont les pauvres et 1 les riches."""
    tableau_de_zero_un = np.zeros((20,20), dtype='i') #np.zeros : renvoie un tableau 1D de 20 zero (lignes) et 20 zero (colonnes)
    for i in range(len(tableau_de_zero_un)): 
        for j in range(len(tableau_de_zero_un)):
            if random.random() < P :
                tableau_de_zero_un[i,j] = 1

    print(tableau_de_zero_un)
    
    return tableau_de_zero_un
    
tab_base = tableauBase(0.6)



[[0 1 0 1 1 0 1 1 1 1 1 0 0 1 1 0 0 0 1 0]
 [1 0 1 1 1 1 0 1 0 1 0 0 0 0 1 1 0 1 1 0]
 [0 1 0 0 1 0 0 0 1 0 1 0 0 1 0 1 1 1 0 1]
 [0 1 0 1 1 1 1 1 0 1 1 1 1 0 1 0 0 1 0 1]
 [0 1 1 1 1 0 1 1 0 1 1 0 1 0 0 1 0 1 0 1]
 [1 1 1 0 1 1 0 1 0 1 1 1 0 1 0 1 0 1 0 0]
 [0 0 0 1 1 1 1 1 1 0 0 1 1 0 1 0 0 0 1 1]
 [0 0 1 0 1 0 0 1 0 1 0 1 1 1 1 0 0 0 1 1]
 [0 1 0 1 1 0 0 1 1 1 1 1 0 1 0 0 0 1 1 0]
 [1 0 0 1 0 0 0 1 0 0 1 1 1 0 1 1 1 0 1 0]
 [1 0 1 1 1 0 1 1 1 1 0 0 1 1 0 0 1 0 0 0]
 [1 0 1 1 0 0 0 1 0 1 1 1 1 1 1 1 1 1 0 0]
 [1 1 0 1 1 0 0 1 0 0 0 1 1 0 0 1 1 1 1 1]
 [1 1 1 0 0 0 1 0 0 0 0 0 1 1 0 1 0 0 1 1]
 [0 1 1 0 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 1]
 [1 1 1 1 1 0 1 0 0 1 1 1 1 1 1 0 0 0 0 1]
 [1 1 0 1 1 1 1 1 1 0 1 0 1 0 1 0 1 1 1 1]
 [1 1 1 1 1 0 0 1 0 1 1 1 1 0 1 1 0 1 1 0]
 [1 1 0 1 1 0 0 1 0 0 1 1 0 1 0 0 0 1 1 0]
 [1 1 0 1 1 0 0 1 0 0 1 0 1 1 0 0 1 1 0 1]]


In [6]:
def verifpop(tabF):
    tab = tabF
    comptC = 0 #compteur consommateurs 
    comptNC = 0 #compteur non-consommateurs 
    for i in range(len(tab)) : #parcours de la matrice 
        for j in range(len(tab)) :#parcours de la matrice 
            if  i+1 <= len(tab) and i-1 >= 0 and  j+1 <= len(tab) and j-1 >= 0:
                if tab[i,j] == 1:
                    comptC = comptC +1
                if tab[i,j] == 0:
                    comptNC = comptNC +1
    return comptC + comptNC


print("Population  :",verifpop(tab_base))

Population  : 361


Ensuite, une nouvelle matrice pour modéliser les consommateurs. A partir d'un certain seuil de pauvreté les 0 se transfermeront en -1.

In [7]:
def influence_se(tab):  #a revoir ! pourquoi pas de -1 ??
    """un carré de 0 crée un groupe de consommateurs (nommé -1)"""
    tableau = tab.copy()
    for i in range(len(tableau)) :
        for j in range(len(tableau)) :
            if  i+1 < len(tableau) and i-1 >= 0 and  j+1 < len(tableau) and j-1 >= 0:
                 if tableau[i,j] == 0 and tableau[i+1,j]==0  and tableau[i,j+1]==0 and tableau[i+1,j+1]==0 :
                    tableau[i,j] = -1
                    tableau[i+1,j]=-1 
                    tableau[i,j+1]=-1
                    tableau[i+1,j+1]=-1           
   
    return tableau

print(influence_se([tab_base]))
# A refaire !! Définir un seuil !!

[array([[0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0],
       [1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0],
       [0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1],
       [0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1],
       [0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1],
       [1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0],
       [0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1],
       [0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1],
       [0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0],
       [1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0],
       [1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0],
       [1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
       [1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1],
       [1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1],
       [0, 1, 1, 0, 1, 1, 1, 1, 1

Le voisinnage : Lorsque un individu est entouré de -1, il voudra déménager. 

In [8]:
def voisins(tab, rowNumber, columnNumber):
    '''
    fonction pour récupérer les voisins
    '''
    N = []
    for i in range(rowNumber-1, rowNumber+2):
        for j in range(columnNumber-1, columnNumber+2):
            if  (i >= 0 and i < tab.shape[0]) and (j >= 0 and j < tab.shape[1]) and ((i,j)!=(rowNumber,columnNumber)):
                N.append(tab[i,j])
    return N

In [10]:
def moyenne_voisins(tab,i,j):
    '''
    Calcul de la moyenne des valeurs voisinnes
    '''
    N = voisins(tab,i,j)
    return sum(N)/len(N)
    
moyenne_voisins(tab_base,4,4)

0.75