# Société 

In [76]:
import matplotlib.pyplot as plt
import numpy as np
import random



Le premier paramètre que nous allons étudier est le le facteur socio-economique. Alors nous allons nous basé en premier lieu sur un système catégorisé : les riches et les pauvres. 
Les riches seront modélisé par des 1 et les pauvres par des 0.



In [94]:
def tableauBase(P):
    """les 0 sont les pauvres et 1 les riches."""
    tableau_de_zero_un = np.zeros((20,20), dtype='i') #np.zeros : renvoie un tableau 1D de 20 zero (lignes) et 20 zero (colonnes)
    for i in range(len(tableau_de_zero_un)): 
        for j in range(len(tableau_de_zero_un)):
            if random.random() < P :
                tableau_de_zero_un[i,j] = 1

    print(tableau_de_zero_un)
    
    return tableau_de_zero_un
    
tab_base = tableauBase(0.6)



[[1 1 0 1 1 0 1 1 0 1 1 0 1 1 1 0 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 0 1 1 0 0 0 0 1 0 1 1]
 [1 0 0 0 1 1 0 1 0 1 1 1 1 0 1 0 1 1 0 1]
 [1 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 0 1 1]
 [1 0 0 1 1 1 0 1 1 1 0 1 1 1 1 1 0 1 0 1]
 [1 1 0 1 1 0 1 0 0 1 1 1 1 1 0 1 1 1 1 0]
 [1 1 1 1 0 0 0 0 0 0 1 0 1 1 1 1 0 0 0 1]
 [1 0 0 1 1 0 0 0 0 1 0 0 0 1 0 1 1 0 0 1]
 [1 0 1 0 0 0 1 1 1 1 0 1 1 0 0 0 0 1 0 1]
 [1 0 1 1 0 1 1 0 0 1 1 0 0 1 1 0 1 1 1 0]
 [1 1 0 0 1 1 1 1 0 0 1 1 1 1 1 1 1 1 0 1]
 [1 1 0 0 1 1 1 1 0 1 1 1 0 1 1 0 0 1 0 0]
 [0 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 1 1 1 1]
 [1 0 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1]
 [0 1 1 0 0 0 1 1 0 1 1 0 1 1 0 0 0 1 1 0]
 [1 1 0 1 1 1 1 1 1 1 0 1 0 0 0 1 1 1 0 1]
 [0 1 1 1 0 1 1 1 1 1 1 0 1 0 1 1 0 1 0 1]
 [1 0 1 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 0 1]
 [0 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 1 0 1 1]
 [1 1 0 1 0 0 1 0 1 1 0 1 1 1 1 0 0 0 0 0]]


In [71]:
def verifpop(tabF):
    tab = tabF
    comptC = 0 #compteur consommateurs 
    comptNC = 0 #compteur non-consommateurs 
    for i in range(len(tab)) : #parcours de la matrice 
        for j in range(len(tab)) :#parcours de la matrice 
            if  i+1 <= len(tab) and i-1 >= 0 and  j+1 <= len(tab) and j-1 >= 0:
                if tab[i,j] == 1:
                    comptC = comptC +1
                if tab[i,j] == 0:
                    comptNC = comptNC +1
    return comptC + comptNC


print("Population  :",verifpop(tab_base))

Population  : 361


In [101]:
def influence_se(tab):  #a revoir ! pourquoi pas de -1 ??
    """un carré de 0 crée un groupe de consommateurs (nommé -1)"""
    tableau = tab.copy()
    for i in range(len(tableau)) :
        for j in range(len(tableau)) :
            if  i+1 < len(tableau) and i-1 >= 0 and  j+1 < len(tableau) and j-1 >= 0:
                 if tableau[i,j] == 0 and tableau[i+1,j]==0  and tableau[i,j+1]==0 and tableau[i+1,j+1]==0 :
                    tableau[i,j] = -1
                    tableau[i+1,j]=-1 
                    tableau[i,j+1]=-1
                    tableau[i+1,j+1]=-1           
   
    return tableau

print(influence_se([tab_base]))

[array([[1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1],
       [1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1],
       [1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1],
       [1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1],
       [1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1],
       [1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1],
       [1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0],
       [1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1],
       [1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0],
       [0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1],
       [1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1],
       [0, 1, 1, 0, 0, 0, 1, 1, 0